### ISSUE TITLE
Localize the app

### ISSUE THREAD

**Issue by dsibinski** [aliyorulmazdev/NC#16]
Please investigate and implement the localization of your app.
What I mean by that is translations in multiple languages. You can add English and Turkish for this exercise 😉

First, make some research on how to store translations.
An additional feature would be that the selected language is remembered for a user and preserved in user's profile (as soon as you have users management in the app)

**Comment by aliyorulmazdev** [comment]
will try to implement this with i18n after i implement login/registar via react.
Sadly never tried it before. should'nt be that hard right? :)
so appuser entity should have language string with default registered "en" or "tr". app should check / load with that language.
so every product has two values instead of one (titleEn, titleTR) etc.

**Comment by aliyorulmazdev** [comment]
temp solved with #23
