### ISSUE TITLE
Research storing data per user

### ISSUE THREAD

**Issue by dsibinski** [aliyorulmazdev/NC#18]
Please make some research on good practices for storing the application's data per user.
We treat your application as a SaaS products, which means that as soon a I register, I get my own _space_ in the app. I want all my data to be private to me and not possible to be seen by other users.

Please read on how to realize that. How to make sure that your API requests only allow fetching the data specific to the user who requests it?
This question is provocative - don't do something like adding a `userId` parameter to your API actions. This won't properly secure the data, as anyone would be able to replace that `userId` with another ID and see the data of another person.
You need to come up with something more robust here.

I want you to first research it and put your findings and ideas for realizing this requirement in this GitHub issue. I want you to write step-by-step how you will realize this requirement.

Only then you can start writing code for it :)

**Comment by aliyorulmazdev** [comment]
My idea is adding appUserId to Product entity. This way products has relation with appUsers.
AppUser(1) to Products(many).

Since i can use _userManager (like i already do on AccountsController)
I can modify my list query to check current user whos making the request via _userManager(ControllerBase.User) than filter products with product.appUserId == User.Id

I dont know if its the correct way to do it. 

Also my ProductsControllers is not ControllerBase class. Maybe i cant use User on there.

**Comment by dsibinski** [comment]
@aliyorulmazdev the direction is good, but it would be nice to somehow ensure that the developer don't accidentally access the data of a wrong user.

In EntityFramework, you could use a Global Query Filter: https://learn.microsoft.com/en-us/ef/core/querying/filters

There's some info here as well: https://learn.microsoft.com/en-us/ef/core/miscellaneous/multitenancy#supporting-multi-tenancy
